name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Generate WireLib make files with CMake
      run: |
        cd WireLib
        mkdir cmake
        cd cmake
    - name: Make WireLib
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Generate DevDisplay make files with CMake
      run: |
        cd devDisplay
        mkdir cmake
        cd cmake
    - name: Make WireLib
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
